---
name: create-docker-image
on:
  push:
  workflow_dispatch:

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker-run
        id: check-container-id
        run: |
          chmod +x script.sh
          docker run -dit --name my-apache-app -p 8080:80 -v "${{ github.workspace }}":/usr/local/apache2/htdocs/ httpd:2.4
          echo "::set-output name=container-id::$(docker ps | grep my-apache-app | awk '{print $1}')"
          docker stop my-apache-app

      - name: docker-commit
        id: check-image-id
        run: |
          echo "${{ steps.check-container-id.outputs.container-id }}"
          docker commit ${{ steps.check-container-id.outputs.container-id }} created-image-step1
          echo docker images | grep created-image-step1 | awk '{print $3}'
          echo "::set-output name=image-id::$(docker images | grep created-image-step1 | awk '{print $3}')"
          docker images

      - name: docker-build
        run: |
          echo "${{ steps.check-image-id.outputs.image-id }}"
          sed -i '1s/^/FROM ${{ steps.check-image-id.outputs.image-id }}\n/' Dockerfile
          echo "check Dockerfile"
          cat Dockerfile
          docker build -t tomyamkung1206/image-sample .
          docker images
          docker ps -a
          docker push tomyamkung1206/image-sample
          # docker run -dit --name confirm-container -p 8080:80 -v "${{ github.workspace }}":/usr/local/apache2/htdocs/ created-image
          # docker ps -a          

  confirm-docker:
    runs-on: ubuntu-latest
    needs: [create-docker-image]
    container: #起動するコンテナイメージを指定
      image: tomyamkung1206/image-sample #指定のdockerイメージを使用
    steps: #dockerコンテナ内でステップを実行
      - name: confirm-inside-docker
        run: |
          find . -name "test.txt"        
          pwd
          ls -al   
          cd /usr/local/apache2/htdocs/
          ls -al
