---
name: create-docker-image
on:
  push:
  workflow_dispatch:

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v3

      - name: docker-run
        id: check-container-id
        run: |
          docker run -dit --name my-apache-app -p 8080:80 -v "${{ github.workspace }}":/usr/local/apache2/htdocs/ httpd:2.4
          echo "::set-output name=container-id::$(docker ps | grep my-apache-app | awk '{print $1}')"
          docker stop my-apache-app

      - name: docker-commit
        id: check-image-id
        run: |
          echo "${{ steps.check-container-id.outputs.container-id }}"
          docker commit ${{ steps.check-container-id.outputs.container-id }} created-image-step1
          echo docker images | grep created-image-step1 | awk '{print $3}'
          echo "::set-output name=image-id::$(docker images | grep created-image-step1 | awk '{print $3}')"
          docker images

      - name: docker-build
        run: |
          echo "${{ steps.check-image-id.outputs.image-id }}"
          sed -i '1s/^/FROM ${{ steps.check-image-id.outputs.image-id }}\n/' Dockerfile
          echo "check Dockerfile"
          cat Dockerfile
          docker build -t created-image .
          docker images

      - name: check-created-image
        run: |
          docker ps -a
          docker run -it --name confirm-container -p 8080:80 -v "${{ github.workspace }}":/usr/local/apache2/htdocs/ created-image
          docker ps -a
          docker exec -it confirm-container bash
          pwd
          ls -al

      - name: crean up workspace after action
        run: |
          sudo rm -rf ${{ github.workspace }}/*
          sudo chown -R $(whoami):$(whoami) .    
