---
name: create-docker-image
on:
  push:
  workflow_dispatch:

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: docker-run
        id: check-container-id
        run: |
          docker run -dit --name my-apache-app -p 8080:80 -v "${{ github.workspace }}":/usr/local/apache2/htdocs/ httpd:2.4
          echo docker ps | grep my-apache-app | awk '{print $1}'
          echo "::set-output name=container-id::$(docker ps | grep my-apache-app | awk '{print $1}')"

      - name: create-docker-image
        run: |
          echo "${{ steps.check-container-id.outputs.container-id }}"